name: Compress Images in Pull Request

on:
  workflow_dispatch: 
  pull_request:
    paths:
      - '**/*.svg'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.webp'
      - '**/*.avif'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: cadamsdev/image-optimizer-action
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        id: compress-images
        uses: cadamsdev/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
